spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/expenses-auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

api:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration-time: ${JWT_EXPIRATION:60}